runtime: python
vm: true
entrypoint: gunicorn -b :$PORT api_project:app

runtime_config:
  python_version: 2

handlers:
- url: /catcomplete
  http_headers:
    Access-Control-Allow-Origin: https://flexible-vm-api-profiler.appspot.com
