runtime: python
vm: true
entrypoint: gunicorn -b :$PORT api_project:app

runtime_config:
  python_version: 2

manual_scaling:
  instances: 1

resources:
  cpu: .5
  memory_gb: 0.18
  disk_size_gb: 10
